module.exports = {
  REST_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
  STORAGE_KEY: 'TRACKS_DEFAULT',
  FULL_DATE_FORMAT: 'yyyy-MM-dd',
  DEFAULT_COUNT: 145,
  HIGHEST_WEIGHT: 175,
  LOWEST_WEIGHT: 115,
};
